### ISSUE TITLE
Upgrade Job: Missing delete endpoint notification for remote clusters

### ISSUE THREAD

**Issue by sridhargaddam** [submariner-io/submariner#1036]
**What happened**:
Latest release to Latest version tests are failing 
https://github.com/submariner-io/submariner/pull/1010/checks?check_run_id=1562617791

The e2e test fails on the [redundancy] job. As part of e2e redundancy tests, we perform a gateway-failover on "cluster2", wait for a new Engine Pod to be created on the newly labelled node and ensure that all connections are established. The last step fails - i.e., connection to cluster1 stays in "connecting..." stage itself.

Looking at the logs on cluster1 enginepod, we see the following error. Also, there is no delete event for cluster2 old endpoint in the logs of cluster1 enginePod. This needs to be investigated and fixed.

cluster1 EnginePod logs: https://pastebin.com/raw/UU0j1cHt

```
2020-12-16T09:26:24.5140018Z [cluster1] E1216 09:20:56.988121       1 tunnel.go:59] error installing cable for Endpoint types.SubmarinerEndpoint{Spec:v1.EndpointSpec{ClusterID:"cluster2", CableName:"submariner-cable-cluster2-172-17-0-10", HealthCheckIP:"10.2.0.1", Hostname:"cluster2-worker2", Subnets:[]string{"100.2.0.0/16", "10.2.0.0/16"}, PrivateIP:"172.17.0.10", PublicIP:"", NATEnabled:false, Backend:"libreswan", BackendConfig:map[string]string(nil)}}, found a pre-existing cable "submariner-cable-cluster2-172-17-0-5" that belongs to this cluster cluster2
```

**What you expected to happen**:
The redundancy test should pass and "cluster1" enginePod should be getting the delete notification for old Endpoint.

**How to reproduce it (as minimally and precisely as possible)**:

**Anything else we need to know?**:

**Environment**:
- Submariner version (use `subctl version`):
- Kubernetes version (use `kubectl version`):
- Cloud provider or hardware configuration:
- OS (e.g: `cat /etc/os-release`):
- Kernel (e.g. `uname -a`):
- Install tools:
- Network plugin and version (if this is a network-related bug):
- Others:

**Comment by tpantelis** [comment]
This issue is specific to upgrade to 0.8.0 which changed the datastore syncer to use admiral. It uses a label, `submariner-io/clusterID`,  on the resources to keep track of the originating cluster to avoid sync loops. In `cluster1`,  we see the initial update for the EP from `cluster2` however notice that the label points to `cluster3`:

<pre>
2020-12-16T09:26:24.4764862Z [cluster1] I1216 09:18:54.403435       1 tunnel.go:51] Tunnel controller processing added
 or updated submariner Endpoint object: &v1.Endpoint{TypeMeta:v1.TypeMeta{Kind:"", APIVersion:""}, 
ObjectMeta:v1.ObjectMeta{Name:"cluster2-submariner-cable-cluster2-172-17-0-5", ... 
Labels:map[string]string{<b>"submariner-io/clusterID":"cluster3"</b>}, Annotations:map[string]string(nil), OwnerReferences:[]v1.OwnerReference(nil), Finalizers:
[]string(nil), ClusterName:"", ManagedFields:[]v1.ManagedFieldsEntry(nil)}, Spec:v1.EndpointSpec{ClusterID:"cluster2", 
CableName:"submariner-cable-cluster2-172-17-0-5", HealthCheckIP:"", Hostname:"cluster2-worker", ...}
</pre>

From the prior release run, it was synced to `cluster3` but w/o the `submariner-io/clusterID` label. On restart after the upgrade, `cluster3` gets notified of the EP from the local datastore and sees that there's no `submariner-io/clusterID` label and assumes it's local so it syncs to the broker. But, in doing so, it sets the `submariner-io/clusterID` label to `cluster3`. `cluster2` eventually sees this and syncs it locally b/c it thinks it's remote. So now the local EP on `cluster2` has the `submariner-io/clusterID` label  set to `cluster3`.  After restart during failover, it deletes it locally but it doesn't get propagated to the broker since it's not seen as local.

Not sure right now how to safely address this - just reporting my initial findings.
