### ISSUE TITLE
implement routing using CNI

### ISSUE THREAD

**Issue by raffaelespazzoli** [submariner-io/submariner#1535]
**What would you like to be added**:

today, if my understating is correct, the routing from a pod that needs to send a packet via the tunnel to the submariner gateway is realized via a set of iptables rules. 
I suggest that routing should be implemented via a CNI plugin (possibly something like this: https://github.com/redhat-nfvpe/cni-route-override).

**Why is this needed**:
This makes routing simpler and more efficient, it de-clutters the iptables host space, also it makes it easier to run the gateway as a normal pod and not in hostntwork space, should that become a requirement.

**Comment by dfarrell07** [comment]
@astoycos @sridhargaddam Had some comments during the PR/Issue they will add.

**Comment by astoycos** [comment]
This Is an interesting idea and could work for ensuring that traffic destined for a remote cluster originating at a non-gateway node makes it to the gateway node without IPTables, however I would be a bit worried about CNI's with "true overlays" where packets never touch the host's routing stack.

For example, today we already do something somewhat similar to this for the OVN-Kuberntes CNI plugin, where the submariner [networkPluginSyncer implements](https://github.com/submariner-io/submariner/pull/1689) some custom OVN logic to ensure traffic is directly routed via gateway nodes, and to the remote cluster without SNAT. 

Ultimately it would be great to to have a CNI agnostic solution to this, and such a solution would be extremely useful to implement, but for the time being we definitely would like to try and keep things consistent as much as possible. And since we need to sometimes perform NAT in Submariner at the gateway (for GlobalNet) it might not be practical to use a routing CNI to get traffic to the GatewayNode and then use Iptables at the gateway node to get traffic to the remote cluster.

**Comment by dfarrell07** [comment]
Talking about this on the scrub, we're not sure if this is a practical solution that meets our needs. Maybe @mkolesnik wants to add details?

**Comment by mkolesnik** [comment]
AFAIK our main problem is not with the routing table, but rather with the way iptables-based CNIs decide to do NAT for traffic leaving from a pod.
That's why we use internal VXLAN tunnels and send traffic through them, to avoid any such problems from the underlying CNI.

If there's some solution for this it might be interesting, but as it stands the proposed solution doesn't cut it.
