### ISSUE TITLE
Is there a roadmap to support kube-proxy in IPVS mode?

### ISSUE THREAD

**Issue by SataQiu** [submariner-io/submariner#1611]
**What would you like to be added**:
Hello! Is there a roadmap to support kube-proxy in IPVS mode?
What needs to be done to implement IPVS support?  And is there a task list?
This seems to be a common need.

Ref: #1559

**Why is this needed**:

**Comment by SataQiu** [comment]
cc @yue9944882

**Comment by skitt** [comment]
As far as I’m aware there is no task list yet, although IPVS is on our radar.

@sridhargaddam, @aswinsuryan, @vthapar — what are the main changes involved in adding IPVS support?

**Comment by yue9944882** [comment]
thanks for replying, submariner team. for kubernetes cluster of larger scale, it's almost mandatory to land on ipvs otherwise traffic rules reloading will be much slower as the # of services grows. not to mention the ipvs tech per se is nowadays considered mature since it's adopted by more and more companies in production. so on the other hand, i believe having such integration w/ ipvs will def help submariner project to extend the user base. 

fwiw, is there any major blocker before we moving towards ipvs?

**Comment by sridhargaddam** [comment]
When Kube-proxy is installed with IPVS mode, kube-proxy programs IPVS load-balancer rules instead of iptable rules.
Currently, Submariner uses iptable rules to preserve the source-IP of the Pods while supporting cross-cluster connectivity.
So we have to check if the iptable rules programmed by Submariner work the way we want even when kube-proxy installs IPVS rules - this investigation is pending.

From a high level, it might require some changes in the Route-agent and Globalnet to support the use-case.

**Comment by dfarrell07** [comment]
@skitt had a call about this today and said the requesters are going to add details so this maybe can be worked on in the 0.13.0 release.

**Comment by KlavsKlavsen** [comment]
We are also running k8s in ipvs mode and would like to test out submariner to connect clusters - so here is to hoping for the v0.13.0 release supporting it :)

**Comment by dfarrell07** [comment]
Talked about this on the PR/Issue scrub, we're still interested in this, if anyone wants to work on it that would be welcome.

**Comment by pratik705** [comment]
We are using proxy in ipvs mode. can anyone help to understand the status of this request? When submariner will support ipvs?

**Comment by sridhargaddam** [comment]
Hello @pratik705, its currently not on the immediate road-map. 
We welcome any contribution if you are interested in working on this feature.

**Comment by zoukewang** [comment]
Are there any support IPVS plans in place now?@[sridhargaddam](https://github.com/sridhargaddam)
