### ISSUE TITLE
1:1 NAT

### ISSUE THREAD

**Issue by mkomu** [submariner-io/submariner#166]
Hi,

I have a question about the 1:1 NAT requirement. From the manual:

"Direct IP connectivity between instances through the internet (or on the same network if not running Submariner over the internet). Submariner supports 1:1 NAT setups, but has a few caveats/provider specific configuration instructions in this configuration."

Does submariner work in the following scenario?

broker cluster:
- gateway/master with public address
- private addresses otherwise

cluster 1:
- gateway/master with public address
- private addresses otherwise

cluster 2:
- private addresses

**Comment by mkomu** [comment]
To rephrase, what in the system design requires 1:1 NAT? Do you require two way connectivity between the clusters?

P.S. Would it help to open some ports in the NATs?

**Comment by dimaunx** [comment]
Currently the broker cluster API must be accessible from both gateway clusters.
The gateway clusters will be pushing changes to the broker.
From the gateway clusters one can be private (no inbound access to the API and no open ports to public or to other clusters) and the second gateway cluster must be accessible from the first private gateway cluster on IPSEC ports UDP 500 and 4500. There is no hard requirement for two way connectivity between the gateway clusters only one way and only on IPSEC ports. No API  connectivity is required between the gateway clusters.
#164 
#157 

To your original question, this scenario works:

broker cluster:
master with public address, API open to public or to cluster1 and cluster2 only
private addresses otherwise

cluster 1:
gateway with public address, inbound ports UDP 500,4500 open to cluster2 or public
private addresses otherwise

cluster 2:
gateway private addresses, outbound ports UDP 500,4500 open to cluster1 or anywhere

Hopefully this answers your question.

**Comment by mkomu** [comment]
Hi Dmitry,

> cluster 1:
> gateway with public address, inbound ports UDP 500,4500 open to cluster2 or public
> private addresses otherwise

I guess this would work if cluster1 gateway has private address but the external public address is known and the ipsec ports are pinholed to the gateway?

**Comment by dimaunx** [comment]
> Hi Dmitry,
> 
> > cluster 1:
> > gateway with public address, inbound ports UDP 500,4500 open to cluster2 or public
> > private addresses otherwise
> 
> I guess this would work if cluster1 gateway has private address but the external public address is known and the ipsec ports are pinholed to the gateway?

Yes you are correct, if you do port forward to the gateway node it will work.

**Comment by mkomu** [comment]
Can you document this (including the port info) to the README since the 1:1 NAT requirement is a bit misleading?

**Comment by nyechiel** [comment]
We just documented this in our docs, please see https://github.com/submariner-io/submariner-website/pull/155.

**Comment by mkomu** [comment]
Thanks!
