### ISSUE TITLE
Add a label for PRs which need to be squashed

### ISSUE THREAD

**Issue by skitt** [submariner-io/submariner#1975]
To reduce the incidence of merged PRs with “review commits”, it would be useful to support a specific “needs-squashing” label, with attendant automation to prevent merges of PRs with that label. This would still allow users to handle the squash, without needing any manual work using `git`, by removing the label and doing a “merge with squash”.

This will need to be implemented at least partially on all repositories.

**Comment by dfarrell07** [comment]
There's a new GH feature that lets you compare across commits, even after amending commits and force-pushing to the same feature branch. Example: https://github.com/submariner-io/submariner/compare/3a096065516201378fc9312b0847cf3153ab4e58..b6e0698fef6e21af50eed9124d753034d271d90f

Given that, think we just shouldn't send commits with changes due to PR feedback. The PR should always be ready to merge.
