### ISSUE TITLE
Avoidability and consequences of asymmetric routing

### ISSUE THREAD

**Issue by adrianrobotka** [submariner-io/submariner#2541]
Hi,

I have just started to work with a new Submariner installation to familiarize myself with Submariner and got stuck before the finish line.
I am asking for a little guideance in this issue, how to orient myself in my situation.

## TL;DR

I've run into the `rp_filter` issue, but I feel that the suggested workaround would be a sub-optimal solution.
I am curious about alternatives.

## Setup

I have created two VPC-based Kubernetes clusters on IBM Cloud with different (pod, service and node) CIDRs:

- Cluster A pods: 172.17.0.X
- Cluster B pods: 172.17.64.Y

## Installation

I used `subctl` to install the latest version of Submariner (0.14.4 and later 0.15.0) on the clusters and created a load balancer for the tunnel (maybe I was not paying attention on a detail, but the tunnel was not established via nat traversal). The CNI is Calico and the extra `IPPool` resources are placed to avoid NAT for external cluster subnets.

### Troubleshooting

Everything works according to:
- `subctl diagnose all`
- `subctl verify --only service-discovery,connectivity --verbose`

**except** gateway <-> non-gateway communication in cross-cluster cases.

I used ping for troubleshooting:
- pod-a: on a non-gateway node in cluster A
- pod-b: on the gateway node in cluster B

The echo-reply reached (back) to the host of pod-a, but **did not** reach pod-a.

root@host-of-pod-a# tcpdump -i ens3 -ln "icmp"
```
07:18:46.168536 IP 172.17.64.Y > 172.17.0.X: ICMP echo reply, id 52341, seq 15, length 64
```

root@pod-a # tcpdump -i eth0 -ln
```
07:38:29.846148 IP 172.17.0.X > 172.17.64.Y: ICMP echo request, id 46944, seq 1025, length 64
07:38:30.870031 IP 172.17.0.X > 172.17.64.Y: ICMP echo request, id 46944, seq 1026, length 64
... # no ICMP reply
```

I've tried to allow all traffic on Calico with an "allow all" in and outbound `GlobalNetworkPolicy`.

root@host-of-pod-a# journalctl -k -f
```
Jun 06 09:23:26 kube-host-name kernel: IPv4: martian source 172.17.0.X from 172.17.64.Y, on dev ens3
```

## My interpretation of the situation

![asymmetric routing between non-gateway and gateway node](https://github.com/submariner-io/submariner/assets/5631349/3f101057-c92b-4140-8629-120a3fbf1d9d)

The root-cause of the martian packets is asymmetric routing. The host of pod-a uses `vx-submariner` to forward outgoing requests, but the cluster's gateway node uses the underlying (VPC) network to forward the replies.

As far as I know, asymmetric routing is ill-advised.
What I found across other issues and on Submariner's Slack is that setting Reverse Path filtering to allow these martian packets is the recommended solution.

I am wondering, does it raise security concenrs to set `rp_filter`? Should it be accompanied by custom firewall rules to guard on source addresses?

Also, I am thinking about the possibility to establish Policy Routing on the gateway node to route the replies (packet with source address from the opposite cluster) through the internal tunnel (`vx-submariner`).
Is it feasible or considered within the project?

Thanks in advance.

**Comment by yboaron** [comment]
Thanks for reaching out @adrianrobotka ,

Theoretically, the best thing would be if the CNIs expose routing API so that Submariner can use this API to set a rule to forward traffic to a remote cluster through the submariner tunnel.

In this case both ingress/egress datapath between clusters should be handled by the CNI, Submariner remains CNI agnostic and there is no need to update rp_filter. This is exactly what we do with OVN-Kubernetes CNI where Submariner does not even create the vx-submariner tunnel interface.

Ideally, we want other CNIs to support similar interfaces, but unfortunately, they don't.

So we are left with two options:

1. Implement both ingress and egress data path between clusters using Submariner
2. Implement only egress between clusters, let CNI handle ingress, and set rp_filter to loose to allow asymmetric traffic.

In order to support ingress traffic coming from a remote cluster to the Pod, Submariner will have to maintain the details of the nodes on which the Pods are scheduled and accordingly route the traffic over the vx-submariner iface to avoid rp_filter requirement. 
Similarly, for services, Submariner will have to re-implement the operations done by Kube-proxy to load-balance the ingress traffic. This is almost like duplicating the work done by the CNI and kube-proxy, hence we avoided this approach. Leaving the ingress datapath to the CNI allows Submariner to work with many CNIs.

Also, we are setting the rp_filter to 2 (aka loose mode) and not disabling the check all together. In Loose mode, the kernel will do some minimal validation on the source address as we can see in the description.

    2 - Loose mode as defined in RFC3704 Loose Reverse Path
        Each incoming packet's source address is also tested against the FIB
        and if the source address is not reachable via any interface
        the packet check will fail.

**Comment by adrianrobotka** [comment]
Thanks @yboaron for the detailed insight!
From this point of view, `rp_filter=2` makes much sense.
