### ISSUE TITLE
I install submariner on dev-cluster and test-cluster

### ISSUE THREAD

**Issue by andyzheung** [submariner-io/submariner#2619]
**What happened**:

I install submariner on dev-cluster and test-cluster.
but I find that my dev-cluster and test-cluster pod all can't access the ip outside the cluster.

and then I uninstall the submariner use this:
https://submariner.io/operations/cleanup/
subctl uninstall --kubeconfig 

and I delete the submariner but i find the vx-submariner is not deleted.
and Iptables also not delete.

**What you expected to happen**:

How can i restore this two cluster?

**How to reproduce it (as minimally and precisely as possible)**:

**Anything else we need to know?**:

**Environment**:
- Diagnose information (use `subctl diagnose all`):
- Gather information (use `subctl gather`):
- Cloud provider or hardware configuration:
- Install tools:
- Others:

**Comment by dfarrell07** [comment]
There's a step in the cleanup docs to remove vx-submariner, see:

```
Delete the vx-submariner interface

On all nodes in each participating cluster, issue the following command:

ip link delete vx-submariner
```

https://submariner.io/operations/cleanup/

We recommend using `subctl uninstall` though, instead of the manual process. If that runs into issues, please let us know.

Not sure about the connectivity issue, we'd need more info about the setup and how you deployed Submariner.

**Comment by dfarrell07** [comment]
Closing for now, feel free to re-open or open another issue if there's still stuff to discuss.
