### ISSUE TITLE
Uninstalling submariner doesn't terminate the namespace

### ISSUE THREAD

**Issue by dirajag1** [submariner-io/submariner#2677]
**What happened**:
Uninstalling submariner doesnt terminate the submariner-operator namespace in both the clusters

**What you expected to happen**:
submariner-operator namespace should get terminated 

**How to reproduce it (as minimally and precisely as possible)**:
Install submariner 
```
subctl deploy-broker --operator-debug --kubeconfig=/tmp/rackA

subctl join --kubeconfig=/tmp/rackA --operator-debug --pod-debug -- clusterid=rack-A broker-info.subm
subctl join --kubeconfig=/tmp/rackB --operator-debug --pod-debug -- clusterid=rack-B broker-info.subm


```

Uninstall submariner

```
subctl uninstall --kubeconfig=/tmp/rackA
subctl uninstall --kubeconfig=/tmp/rackB

```
Namespace in Terminating state
```
# oc get ns | grep subm

submariner-operator                                Terminating  


```

**Anything else we need to know?**:
Same behaviour on OCP versions 4.10 and 4.12 , and submariner versions 0.12 and 0.14.6

**Environment**:
- Diagnose information (use `subctl diagnose all`):
- Gather information (use `subctl gather`):
- Cloud provider or hardware configuration:
- Install tools:
- Others:

**Comment by skitt** [comment]
Could you provide the archive produced by `subctl gather`?

**Comment by dfarrell07** [comment]
FYI, this seems to be being discussed in various places (at least also Slack).

**Comment by dfarrell07** [comment]
> Could you provide the archive produced by subctl gather?

Did this get provided somewhere else? Might be good to include here.

**Comment by dirajag1** [comment]
We were not able to get any logs using the commands mentioned above

**Comment by sridhargaddam** [comment]
> We were not able to get any logs using the commands mentioned above

Did the command (`subctl gather --kubeconfig ...`) run successfully or did it return any errors?

**Comment by jinglina** [comment]
in my case,  CRDs like submariner and servicediscovery cannot be deleted when using uninstall command, so the ns submariner-operator cannot be deleted (keep terminating status).

**Comment by sridhargaddam** [comment]
> in my case, CRDs like submariner and servicediscovery cannot be deleted when using uninstall command, so the ns submariner-operator cannot be deleted (keep terminating status).

As part of uninstall command, the submariner-operator pod would trigger a cleanup of various components and finally deletes the submariner and servicediscovery CRDS along with the submariner-operator namespace. In order to understand why this is not happening, we would need the logs (and archive) of `subctl gather ...`.

**Comment by jinglina** [comment]
Ok, just a moment

**Comment by jinglina** [comment]
[root@node3 ~]# subctl gather all
Cluster "cluster.local"
Gathering information from cluster "cluster.local"
 ✓ Gathering operator logs
 ✓ Gathering operator resources
 ✓ Found 1 submariners in namespace "submariner-operator"
 ✓ Found 1 servicediscoveries in namespace "submariner-operator"
 ✓ Found 0 deployments by field selector "metadata.name=submariner-operator" in namespace "submariner-operator"
 ✓ Found 0 daemonsets by label selector "app=submariner-gateway" in namespace "submariner-operator"
 ✓ Found 0 daemonsets by label selector "app=submariner-metrics-proxy" in namespace "submariner-operator"
 ✓ Found 0 daemonsets by label selector "app=submariner-routeagent" in namespace "submariner-operator"
 ✓ Found 0 daemonsets by label selector "app=submariner-globalnet" in namespace "submariner-operator"
 ✓ Found 0 deployments by label selector "app=submariner-networkplugin-syncer" in namespace "submariner-operator"
 ✓ Found 0 deployments by label selector "app=submariner-lighthouse-agent" in namespace "submariner-operator"
 ✓ Found 0 deployments by label selector "app=submariner-lighthouse-coredns" in namespace "submariner-operator"
 ✓ Gathering connectivity logs
 ✓ Found 0 pods matching label selector "app=submariner-gateway"
 ✓ Found 0 pods matching label selector "app=submariner-routeagent"
 ✓ Found 0 pods matching label selector "app=submariner-metrics-proxy"
 ✓ Found 0 pods matching label selector "app=submariner-metrics-proxy"
 ✓ Found 0 pods matching label selector "app=submariner-globalnet"
 ✓ Found 0 pods matching label selector "app=submariner-networkplugin-syncer"
 ✓ Found 0 pods matching label selector "app=submariner-addon"
 ✓ Gathering connectivity resources
 ✓ Gathering CNI data from 0 pods matching label selector "app=submariner-routeagent"
 ✓ Gathering CNI data from 0 pods matching label selector "app=submariner-gateway"
 ✓ Gathering cable driver data from 0 pods matching label selector "app=submariner-gateway"
 ✓ Found 0 endpoints in namespace "submariner-operator"
 ✓ Found 0 clusters in namespace "submariner-operator"
 ✓ Found 0 gateways in namespace "submariner-operator"
 ✓ Found 1 clusterglobalegressips in namespace ""
 ✓ Found 0 globalegressips in namespace ""
 ✓ Found 0 globalingressips in namespace ""
 ✓ Gathering service-discovery logs
 ✓ Found 0 pods matching label selector "component=submariner-lighthouse"
 ✓ Found 2 pods matching label selector "k8s-app=kube-dns"
 ✓ Gathering service-discovery resources
 ✓ Found 0 serviceexports in namespace ""
 ✓ Found 1 serviceimports in namespace ""
 ✓ Found 1 endpointslices by label selector "endpointslice.kubernetes.io/managed-by=lighthouse-agent.submariner.io" in namespace ""
 ✓ Found 0 configmaps by label selector "component=submariner-lighthouse" in namespace "submariner-operator"
 ✓ Found 1 configmaps by field selector "metadata.name=coredns" in namespace "kube-system"
 ✓ Found 1 services by label selector "submariner.io/exportedServiceRef" in namespace ""
 ✓ Gathering broker logs
 ✗ Gathering broker resources
 ✓ Found 9 endpoints in namespace "submariner-k8s-broker"
 ✓ Found 4 clusters in namespace "submariner-k8s-broker"
 ✗ Failed to gather endpointslices: error listing "endpointslices": the server could not find the requested resource
 ✓ Found 2 serviceimports in namespace "submariner-k8s-broker"

**Comment by jinglina** [comment]
[root@node3 ~]# subctl diagnose all
Cluster "cluster.local"
 ✓ Checking Submariner support for the Kubernetes version
 ✓ Kubernetes version "v1.23.7" is supported

 ✓ Globalnet deployment detected - checking if globalnet CIDRs overlap
 ✓ Clusters do not have overlapping globalnet CIDRs
 ✗ Checking DaemonSet "submariner-gateway"
 ✗ Error obtaining Daemonset "submariner-gateway": daemonsets.apps "submariner-gateway" not found
 ✗ Checking DaemonSet "submariner-routeagent"
 ✗ Error obtaining Daemonset "submariner-routeagent": daemonsets.apps "submariner-routeagent" not found
 ✗ Checking DaemonSet "submariner-globalnet"
 ✗ Error obtaining Daemonset "submariner-globalnet": daemonsets.apps "submariner-globalnet" not found
 ✗ Checking DaemonSet "submariner-metrics-proxy"
 ✗ Error obtaining Daemonset "submariner-metrics-proxy": daemonsets.apps "submariner-metrics-proxy" not found
 ✗ Checking Deployment "submariner-lighthouse-agent"
 ✗ Error obtaining Deployment "submariner-lighthouse-agent": deployments.apps "submariner-lighthouse-agent" not found
 ✗ Checking Deployment "submariner-lighthouse-coredns"
 ✗ Error obtaining Deployment "submariner-lighthouse-coredns": deployments.apps "submariner-lighthouse-coredns" not found
 ✓ Checking the status of all Submariner pods
 ✗ Checking if gateway metrics are accessible from non-gateway nodes
 ✗ Error spawning the client pod on non-Gateway node: error scheduling pod: error creating Pod: pods "validate-client" is forbidden: unable to create new content in namespace submariner-operator because it is being terminated
 ✗ Checking if globalnet metrics are accessible from non-gateway nodes
 ✗ Error spawning the client pod on non-Gateway node: error scheduling pod: error creating Pod: pods "validate-client" is forbidden: unable to create new content in namespace submariner-operator because it is being terminated

 ✓ Checking Submariner support for the CNI network plugin
 ✓ The detected CNI network plugin ("calico") is supported
 ✗ Calico CNI detected, checking if the Submariner IPPool pre-requisites are configured
 ✗ No gateways detected on the cluster
 ✗ Checking gateway connections
 ✗ No gateways were detected
 ✗ Checking Submariner support for the kube-proxy mode
 ✗ Error spawning the network pod: error creating Pod: pods "query-iface-list" is forbidden: unable to create new content in namespace submariner-operator because it is being terminated
 ✗ Checking the firewall configuration to determine if intra-cluster VXLAN traffic is allowed
 ✗ Unable to obtain a remote endpoint: endpoints.submariner.io "remote Endpoint" not found
 ✓ Checking Globalnet configuration
 ✓ Globalnet is properly configured and functioning

 ✓ Checking if services have been exported properly
 ✓ All services have been exported properly

Skipping inter-cluster firewall check as it requires two kubeconfigs. Please run "subctl diagnose firewall inter-cluster" command manually.

subctl version: devel

**Comment by jinglina** [comment]
![diagnose](https://github.com/submariner-io/submariner/assets/30133396/270996d0-29a0-4301-8945-fdc3cc43b179)

**Comment by jinglina** [comment]
I noticed submariner and servicediscovery crd shows 
```
finalizers:
- controllers.submariner.io/cleanup
```
maybe it means something

**Comment by jinglina** [comment]
the image version used is v0.15.2

**Comment by sridhargaddam** [comment]
> ✓ Found 0 deployments by field selector "metadata.name=submariner-operator" in namespace "submariner-operator"
✓ Found 0 daemonsets by label selector "app=submariner-gateway" in namespace "submariner-operator"
✓ Found 0 daemonsets by label selector "app=submariner-metrics-proxy" in namespace "submariner-operator"
✓ Found 0 daemonsets by label selector "app=submariner-routeagent" in namespace "submariner-operator"
✓ Found 0 daemonsets by label selector "app=submariner-globalnet" in namespace "submariner-operator"
✓ Found 0 deployments by label selector "app=submariner-networkplugin-syncer" in namespace "submariner-operator"
✓ Found 0 deployments by label selector "app=submariner-lighthouse-agent" in namespace "submariner-operator"
✓ Found 0 deployments by label selector "app=submariner-lighthouse-coredns" in namespace "submariner-operator"

This implies that none of the Submariner pods are currently running in the `submariner-operator` namespace. As I mentioned above, the submariner-operator Pod after performing the necessary cleanup will remove the finalizer `controllers.submariner.io/cleanup` from the `submariner` and `servicediscovery` CRDs. We would need the logs of the submariner-operator pod to understand why it was unable to delete the finalizer from the CRDs.

Since the Pod is no longer running, there is not much we can do in the current setup. So, can you try the following?
1. manually delete the finalizers from the two CRDs and delete the submariner-operator namespace.
2. Repeat the above operation on the second cluster and ensure that submariner-operator is completed deleted.
3. Re-install Submariner on the clusters.
4. After Submariner is installed and connections are established, run the command `subctl gather --kubeconfig ...` and tar/zip the directory where the files are stored. For example, you will find the following line at the end of the `subctl gather ...` command output - `Files are stored under directory "logs/cluster2"`
5. Now run `subctl uninstall ...` command and in parallel capture the logs of submariner-operator pod 

Please share the output of 4 and 5 steps above.

**Comment by tpantelis** [comment]
A couple things of note. You state that the 2 connected clusters are running submariner versions _0.12_ and _0.14.6_. I'm not sure we support a mixed submariner version environment. Also you're running the latest _devel_ version of `subctl`, at least to perform `gather`  - I assume you used the same `subctl` to run uninstall. You really should use the same version of `subctl` as is the version of submariner running in the cluster.

That said, as @sridhargaddam mentioned, since the submariner-operator deployment is gone, there's isn't much we can tell w/o the pod logs. So, if you can try to reproduce,  I'd suggest to use kubectl to tail/follow the submariner-operator log and then run `subctl uninstall` and provide the log output and the `subctl` output.

**Comment by jinglina** [comment]
In my case, it came up time to time, and cannot figure out the reproduce process of appearing necessarily.

**Comment by sridhargaddam** [comment]
Okay, so its not consistent and is seen only intermittently. Anyways, without access to logs, its hard to understand what is going on. When you see this problem once again, please attach the required logs.

**Comment by dfarrell07** [comment]
Closing as this is quite stale. Feel free to re-open if the issue pops up and we can get the logs.
