### ISSUE TITLE
"report-dir" argument can be removed (Ginkgo has --reportFile option)

### ISSUE THREAD

**Issue by manosnoam** [submariner-io/submariner#276]
"report-dir" argument for specifying junit tests output directory - can be removed, including any references that uses it (also in Docs):
https://github.com/submariner-io/submariner/blob/06332b91b193c0ab362e7f0a96cd715b8556acd5/test/e2e/framework/test_context.go#L40

Ginkgo has this feature already, for example
--ginkgo.reportFile ${WORKDIR}/e2e_junit_result.xml

**Comment by mangelajo** [comment]
@manosnoam do you have the time to send a patch for this, since you are more familiar?

**Comment by manosnoam** [comment]
@pinikomarov can you look at it ?

**Comment by pinikomarov** [comment]
sure I'll take a look

**Comment by pinikomarov** [comment]
@manosnoam @tfreger, I created two drafts for this:
 I'll test them out and update
https://github.com/submariner-io/submariner/pull/629
https://github.com/submariner-io/shipyard/pull/203

**Comment by pinikomarov** [comment]
@mkolesnik @manosnoam @mangelajo   can you advice here ? 
we want to remove the usage of report-dir in shipyard.
and I'm looking where to remove code from shipyard/test/e2e/e2e.go.
so looking at this change : 
https://github.com/onsi/ginkgo/pull/601#issue-313279375

This means that there is no need for reporterList and reportDir from e2e.go:  ?
https://github.com/submariner-io/shipyard/blob/fa055d2e6a5ebae16cd958664b9d7d6210ca47d4/test/e2e/e2e.go#L58

and also we can remove this whole section ? 
Since there is no need to create any dirs/files/or prefixes since they can be specified by using the
-ginkgo.reportFile <file path> option.

```
	reporterList := []ginkgo.Reporter{}
	reportDir := framework.TestContext.ReportDir
	if reportDir != "" {
		// Create the directory if it doesn't already exists
		if err := os.MkdirAll(reportDir, 0755); err != nil {
			t.Fatalf("Failed creating jUnit report directory: %v", err)
			return false
		}
	}
	// Configure a junit reporter to write to the directory
	junitFile := fmt.Sprintf("junit_%s_%02d.xml",
		framework.TestContext.ReportPrefix,
		config.GinkgoConfig.ParallelNode)
	junitPath := filepath.Join(reportDir, junitFile)
	reporterList = append(reporterList, reporters.NewJUnitReporter(junitPath))
	return ginkgo.RunSpecsWithDefaultAndCustomReporters(t, "Submariner E2E suite", reporterList)
}
```
at : https://github.com/submariner-io/shipyard/blob/fa055d2e6a5ebae16cd958664b9d7d6210ca47d4/test/e2e/e2e.go#L58

And finally the return function question : 
we finish e2e.go with:
func RunE2ETests(t *testing.T) bool {
by : 
return ginkgo.RunSpecsWithDefaultAndCustomReporters(t, "Submariner E2E suite", reporterList)

what return code should I use here ?
isn't reporterList created by default by ginkgo ? at : 
https://github.com/onsi/ginkgo/blob/83bb20e89959e9eb3cb1508635c67d281ea1406c/ginkgo_dsl.go#L205

Thanks

**Comment by mangelajo** [comment]
Are you sure that you don't need to create the reporters anymore? 

https://github.com/onsi/ginkgo/pull/601#issuecomment-568877348 ? 

You can try to remove those sections and run "make e2e" in shipyard, the framework will get executed and smoke-tested.


About the return, I don't know, check for other ginkgo runners? look at the examples probably the default runner without custom reporters? But... I really think that if you don't add the reporterList with Junit you will stop getting junit

**Comment by mangelajo** [comment]
Ahh, for the return look here:

https://github.com/onsi/ginkgo/pull/601/files#diff-e3fb4e75aa5d5eae55da62367a741ea5R200

You probably need to call simply RunSpecs now?

**Comment by manosnoam** [comment]
> and also we can remove this whole section ?
> Since there is no need to create any dirs/files/or prefixes since they can be specified by using the
> -ginkgo.reportFile option.
> 
> ```
> 	reporterList := []ginkgo.Reporter{}
> 	reportDir := framework.TestContext.ReportDir
> 	if reportDir != "" {
> 		// Create the directory if it doesn't already exists
> 		if err := os.MkdirAll(reportDir, 0755); err != nil {
> 			t.Fatalf("Failed creating jUnit report directory: %v", err)
> 			return false
> 		}
> 	}
> 	// Configure a junit reporter to write to the directory
> 	junitFile := fmt.Sprintf("junit_%s_%02d.xml",
> 		framework.TestContext.ReportPrefix,
> 		config.GinkgoConfig.ParallelNode)
> 	junitPath := filepath.Join(reportDir, junitFile)
> 	reporterList = append(reporterList, reporters.NewJUnitReporter(junitPath))
> 	return ginkgo.RunSpecsWithDefaultAndCustomReporters(t, "Submariner E2E suite", reporterList)

Yes, I think you can remove it, as onsi/ginkgo#601 executes RunSpecsWithDefaultAndCustomReporters(...)

**Comment by pinikomarov** [comment]
alright thanks gentleman I got the idea,
action plan :
I'll gradually remove code and execute make e2e until the code is stable

Thanks

**Comment by pinikomarov** [comment]
@manosnoam @mangelajo  ok commits are ready for reviews :
https://github.com/submariner-io/shipyard/pull/216
https://github.com/submariner-io/submariner/pull/629
Thanks

**Comment by pinikomarov** [comment]
all patches merged , closing and thanks :)
