### ISSUE TITLE
The packets loss on the node's for interfaces when submariner gateway is active on node

### ISSUE THREAD

**Issue by surfinlemex** [submariner-io/submariner#2875]
We have implemented submariner using HELM charts into an Openshift 4.12.28 cluster running on Dell hardware.
Worker nodes have one of the following configurations :
   2 X Intel X710 NIC's
   2 X Mellanox MT27800
The 2 NIC's are bonded together with LACP (802.3ad) using 1 port from each NIC.

We have configured multiple tagged vLAN's as sub-interfaces on top of this bonded interface.
The 2 ports of each NIC are connected to a pair of switches in stack (CISCO Nexus)
We want submariner to use one of the tagged vLAN's for communication between the 2 clusters.

We have 3 gateway nodes and are using VXLAN as the cable driver.
The problem was initially seen as latency of communication between pods on the 2 clusters.
We see packets loss (using ping command) on all sub-interfaces only on the worker node that is running the active gateway. This packet loss is to all other workers in the cluster. 

This packet loss only happens on the workers with Intel NIC's. There is no issue with Mellanox MT27800 cards.

We haven't seen any anomaly related to configuration or events on the CISCO Nexus switches.

If we enable promisciuous mode on the port (by taking a tcpdump), then the problem is not observered.

If the switchport mode on the switch is changed to access from trunk, and the worker node reconfigured to use physical interface without sub-interface, then we do not observe the packet loss.

We can provide a TCP dump of the interaction between the worker nodes and the switches.
the firmware for the Intel NIC's is currently in the process of being upgraded to the latest version as it is 9 months old.

Is there anything we can check from the submariner side to maybe get some evidence to provide to Intel ?

**Comment by yboaron** [comment]
This seems like a platform/infra issue, not something related to Submariner.

A. To verify it's a network/infra issue, you can test connectivity over VxLAN, by manually creating a VxLAN tunnel between two worker nodes (something like [this link](https://github.com/nehalineogi/azure-cross-solution-network-architectures/blob/main/advanced-linux-networking/linux-vxlan.md)) .

B. Also, maybe you can disable the UDP checksum offload (using [1] command ) on the relevant interfaces (vx-submariner if your CNI=OpenShiftSDN and since you are using VxLAN as a cable driver, you should also apply this to the physical interface on the GW node ) and see if that helps?

[1]
ethtool --offload <nic_name> rx off tx off

**Comment by dfarrell07** [comment]
@surfinlemex Did @yboaron's suggestions resolve/clarify things? Can we close this?

**Comment by dfarrell07** [comment]
Closing for now, feel free to re-open if more discussion is needed.
