### ISSUE TITLE
Wireguard gateway failover tests fails in 0.18

### ISSUE THREAD

**Issue by aswinsuryan** [submariner-io/submariner#3031]
**What happened**:Wireguard gateway failover tests fails in 0.18

**What you expected to happen**: The tests should pass 

**How to reproduce it (as minimally and precisely as possible)**: Run e2e in 0.18 branch, the logs are attached.

**Anything else we need to know?**:

**Environment**:
- Diagnose information (use `subctl diagnose all`):
- Gather information (use `subctl gather`):
- Cloud provider or hardware configuration:
- Install tools:
- Others:
[
[submariner-gather.zip](https://github.com/user-attachments/files/15517245/submariner-gather.zip)
](url)

**Comment by tpantelis** [comment]
I tried E2E with K8s 1.28 and it worked. So the issue is with 1.29 at least.

**Comment by yboaron** [comment]
The root cause for this issue is wireguard **submariner** network interface created with new ifindex after GW pod restarted, meaning all host routes created in route agent pod with LinkIndex pointing to previous wireguard **submariner**  ifindex are deleted.

To workaround this issue we can restart the route-agent pod on gateway node.
