### ISSUE TITLE
[RFE] Support enabling globalnet annotation per-namespace

### ISSUE THREAD

**Issue by mangelajo** [submariner-io/submariner#528]
Globalnet IP address space is limited, and in some use cases, where clusters are multi-tenant  / shared, administrators may only want to inter-connect specific namespaces only.

In that case the IP address usage in globalnet could be greatly reduced if the namespaces were opted in to the global-net ips.

If pods/services on a specific namespace want to participate in globalnet, we can either create a resource on that namespace, or flag the namespace so submariner will start processing it, and assigning globalIPs for remote connectivity.

source for this request: @jds2001

**Comment by vthapar** [comment]
We're looking to implement changes proposed in https://github.com/kubernetes/enhancements/pull/1646 for service discovery. Part of this requires services to be explicitly tagged to be imported by crating ServiceExport objects i.e. an opt-in model instead of the all-in default we have today. It would make sense to reuse it to determine which services need a global IP.

Whatever mechanism we decide for opt-in, annotations etc., can easily implement tooling in subctl to do the tagging/annotations for all pods/services in a single namespace. This will keep things simple and at same time make it easier for admins to make all services and pods in specific namespaces multicluster aware, without needing explicit globalcidr per namespace.

**Comment by sridhargaddam** [comment]
The following enhancement request would handle this use-case - https://github.com/submariner-io/submariner/issues/652

**Comment by nyechiel** [comment]
bump
