### ISSUE TITLE
SYN packet loss with Globalnet -- causing long or failed tests

### ISSUE THREAD

**Issue by deanlorenz** [submariner-io/submariner#567]
@sridhargaddam @mangelajo

Long e2e tests (Ran 9 of 20 Specs in 364.925 seconds)

**Probable cause**: SYN packet drop on first attempt of each test.
TCP gives up after repeated TOs. Retry succeeds.
Often at test will fail due to TO.
Seems like SYN is routed OK within the sending cluster

Example:
![image](https://user-images.githubusercontent.com/8469923/81966179-cddb2600-9621-11ea-9c99-00098629ff97.png)

Another:
![image](https://user-images.githubusercontent.com/8469923/81966265-f400c600-9621-11ea-8c9c-8a0a7de6a9ec.png)
Full test tcpdump: 
[e2e-gn-helm.log](https://github.com/submariner-io/submariner/files/4630020/e2e-gn-helm.log)

Generated with:
```shell
n=(2 3)
for nn in 0 1; do
  for i in weave vx-submariner subwg0; do
    for c in cluster${n[$nn]}-worker{,2}; do
      docker exec $c ip -4 l | grep -q $i && docker exec $c tcpdump -l -n -i $i net 10.24${n[$((1-nn))]}.0.0/16 or 169.254.0.0/16 2>&1 > $c-$i.pcap & 
	done & 
  done & 
done

<<< RUN E2E TEST >>>

for c in cluster{2,3}-worker{,2}; do
  docker exec -it $c pkill tcpdump
done

grep -iIs . cluster{2,3}*.pcap | 
  sort -n -t: -k2 -k3 -k4 | 
  sed 's/\(^[^:]*\):/\1\t/' | 
  sed 's/vx-submariner/vxsub/'| 
  sed 's/options .*\], //'
```

**Comment by sridhargaddam** [comment]
In the current e2e tests, we do not wait for the netshoot (aka client/connector) Pod to get a globalIP annotation and the Pod, as soon as it enters running state, it tries to connect to the remote service IP (which is passed as an environment variable). Since the globalIP annotation and programming of the corresponding iptable rules happen asynchronously we can see this kind of issues. Once Globalnet is enhanced to support a default cluster-wide globalIP, this issue should be resolved.
