### ISSUE TITLE
Add automated test coverage for MacOS

### ISSUE THREAD

**Issue by nyechiel** [submariner-io/submariner#577]
**What would you like to be added**:

An automated job running the Submariner e2e tests on Mac.

**Why is this needed**:

Catch issues that might be specific to MacOS.

**Comment by mangelajo** [comment]
I don’t think this will be possible. Docker on OS X is a vm with Linux. That means vm in vm ... very likely not worth the effort of even trying.

**Comment by nyechiel** [comment]
Yes, I realized the same. @mkolesnik is there anything you think we can do here? If not, let's close this one.

**Comment by mkolesnik** [comment]
Indeed, GitHub hosted runners do support macos, but they don't have docker installed there (and probably never will, unless Apple foots the bill?).

Hence, you'd first need to install community docker and as @mangelajo mentioned, it'll have to be a VM that's running docker itself, and since the CI is already running in a VM this becomes much more difficult.
