### ISSUE TITLE
Submariner behavior when Broker cluster is down

### ISSUE THREAD

**Issue by sridhargaddam** [submariner-io/submariner#789]
It would be helpful to understand the behavior of various Submariner use-cases when the Broker cluster goes down. 

In this process, create new issues for any problems that are seen and fix them. Also, document the behavior on the website.

**Comment by nyechiel** [comment]
We need to verify:

1) What happens when the Broker goes down?
2) How the system behaves once the Broker comes back up?

**Comment by tpantelis** [comment]
Results are in for the submariner engine:

> 1. What happens when the Broker goes down?

The informer loses connection but keeps running although it's very chatty with frequent, periodic log messages. This does not affect the dataplane.

> 2. How the system behaves once the Broker comes back up?

The informer reestablishes connection and re-syncs all current resources, ie a create notification is issued for all pre-existing resources. Subsequent notifications are delivered as expected. So the transition works smoothly.

> 3. What happens when the Broker is down when the engine process starts up?

Startup fails and exits due to the permissions access check to the broker API server. This check is done in the `getCheckedBrokerClientset` function in the broker syncer (added by @skitt).  This is problematic for the engine since this prevents the dataplane components from running as well if the broker is unavailable. This would be avoided if we separate the syncer into its own process. Regardless it seems reasonable to only fail if a permissions error occurs since that's the purpose of the check. It's possible the broker could be unavailable **and** the permissions are incorrect but I think that's an edge case. I submitted https://github.com/submariner-io/admiral/pull/140 for review if folks think this is a reasonable approach. With this change the process starts up fine otherwise.

**Comment by nyechiel** [comment]
Thanks @tpantelis. Following our discussion on this, it would be useful to also test/confirm the impact on Lighthouse. Also, I think it's a good idea to document this as part of https://submariner.io/architecture/broker/

**Comment by tpantelis** [comment]
Results for the lighthouse agent are similar to that of the submariner engine except that when a service is exported when the broker is down, the `ServiceImport` isn't created at all.  This is b/c it creates it on the broker first and syncs locally from the broker. We should consider creating it locally first as the submariner engine does.

**Comment by mkolesnik** [comment]
I guess my question would be - What should we expect to happen when broker is down (or unreachable)?

From my perspective we should strive for Submariner as a whole (and all individual parts) to be as resilient as possible, and as such I would expect it to keep working with last known state in case the broker is down and sync up whenever broker comes back up.

**Comment by tpantelis** [comment]
> Results for the lighthouse agent are similar to that of the submariner engine except that when a service is exported when the broker is down, the `ServiceImport` isn't created. This is b/c it creates it on the broker first and syncs locally from the broker. We should consider creating it locally first as the submariner engine does. It does keep trying so it eventually gets created when the broker comes back.

Addressed by https://github.com/submariner-io/lighthouse/pull/379.

**Comment by tpantelis** [comment]
> Thanks @tpantelis. Following our discussion on this, it would be useful to also test/confirm the impact on Lighthouse. Also, I think it's a good idea to document this as part of https://submariner.io/architecture/broker/ so that users will know what to expect.

https://github.com/submariner-io/submariner-website/pull/370
