### ISSUE TITLE
Unable to run prep_for_subm.sh when both cluster directories are in the same folder

### ISSUE THREAD

**Issue by sridhargaddam** [submariner-io/submariner#876]
**What happened**:

Running into errors when we use ./prep_for_subm.sh with AWS Cluster directories in the same folder.

According to [quickstart guide](https://submariner.io/quickstart/openshift/service_discovery/#make-your-clusters-ready-for-submariner) ideally, we should be able to run the prep_for_subm.sh as shown below
./prep_for_subm.sh cluster-a     # respond yes when terraform asks
./prep_for_subm.sh cluster-b      # respond yes when terraform asks

However, it was seen that after executing the command for cluster-a, when we try to run the same command for cluster-b, its using some info of Cluster-a and giving errors.

```
[sgaddam@localhost aws-ocp]$ ./prep_for_subm.sh cluster-b
infraID: cluster-b-sk6mp
region: us-east-2
Initializing modules...

Initializing the backend...

Initializing provider plugins...

The following providers do not have any version constraints in configuration,
so the latest version was installed.

To prevent automatic upgrades to new major versions that may contain breaking
changes, it is recommended to add version = "..." constraints to the
corresponding provider blocks in configuration, with the constraint strings
suggested below.

* provider.aws: version = "~> 3.10"
* provider.local: version = "~> 1.4"
* provider.null: version = "~> 3.0"
* provider.template: version = "~> 2.2"

Terraform has been successfully initialized!

You may now begin working with Terraform. Try running "terraform plan" to see
any changes that are required for your infrastructure. All Terraform commands
should now work.

If you ever set or change modules or backend configuration for Terraform,
rerun this command to reinitialize your working directory. If you forget, other
commands will detect it and remind you to do so if necessary.
module.ocp-ipi-aws-prep.data.aws_vpc.env_vpc: Refreshing state...
module.ocp-ipi-aws-prep.data.aws_subnet_ids.env_vpc_public_subnets: Refreshing state...
module.ocp-ipi-aws-prep.data.aws_instances.worker_instances: Refreshing state...
module.ocp-ipi-aws-prep.data.aws_security_group.worker_sg: Refreshing state...
module.ocp-ipi-aws-prep.aws_security_group.submariner_gw_sg: Refreshing state... [id=sg-0ad55ffc9df0a0f0e]
module.ocp-ipi-aws-prep.data.aws_subnet.target_public_subnet: Refreshing state...
module.ocp-ipi-aws-prep.aws_security_group_rule.worker_sg_vxlan_rule: Refreshing state... [id=sgrule-753854759]
module.ocp-ipi-aws-prep.data.aws_instance.worker_instance: Refreshing state...
module.ocp-ipi-aws-prep.null_resource.target_subnet_tags: Refreshing state... [id=912029728]
module.ocp-ipi-aws-prep.null_resource.empty_file: Refreshing state... [id=422661962]
module.ocp-ipi-aws-prep.local_file.machine_set_config: Refreshing state... [id=d2d1d9687af289c5619c487f18a3ac3e1163230b]

An execution plan has been generated and is shown below.
Resource actions are indicated with the following symbols:
  ~ update in-place
-/+ destroy and then create replacement
 <= read (data resources)

Terraform will perform the following actions:

  # module.ocp-ipi-aws-prep.data.template_file.machine_set_template will be read during apply
  # (config refers to values not yet known)
 <= data "template_file" "machine_set_template"  {
      + id       = (known after apply)
      + rendered = (known after apply)
      + template = "---\napiVersion: machine.openshift.io/v1beta1\nkind: MachineSet\nmetadata:\n  labels:\n    machine.openshift.io/cluster-api-cluster: ${cluster_id}\n  name: ${cluster_id}-submariner-gw-${az}\n  namespace: openshift-machine-api\nspec:\n  replicas: 1\n  selector:\n    matchLabels:\n      machine.openshift.io/cluster-api-cluster: ${cluster_id}\n      machine.openshift.io/cluster-api-machineset: ${cluster_id}-submariner-gw-${az}\n  template:\n    metadata:\n      creationTimestamp: null\n      labels:\n        machine.openshift.io/cluster-api-cluster: ${cluster_id}\n        machine.openshift.io/cluster-api-machine-role: worker\n        machine.openshift.io/cluster-api-machine-type: worker\n        machine.openshift.io/cluster-api-machineset: ${cluster_id}-submariner-gw-${az}\n    spec:\n      metadata:\n        labels:\n          submariner.io/gateway: \"true\"\n      taints:\n        - effect: NoSchedule\n          key: node-role.submariner.io/gateway\n      providerSpec:\n        value:\n          ami:\n            id: ${rhos_ami_id}\n          apiVersion: awsproviderconfig.openshift.io/v1beta1\n          credentialsSecret:\n            name: aws-cloud-credentials\n          deviceIndex: 0\n          iamInstanceProfile:\n            id: ${cluster_id}-worker-profile\n          instanceType: m5n.large\n          kind: AWSMachineProviderConfig\n          placement:\n            availabilityZone: ${az}\n            region: ${aws_region}\n          securityGroups:\n            - filters:\n                - name: tag:Name\n                  values:\n                    - ${cluster_id}-worker-sg\n                    - ${submariner_sg_name}\n          subnet:\n            filters:\n              - name: tag:Name\n                values:\n                  - ${public_subnet_name}\n          tags:\n            - name: kubernetes.io/cluster/${cluster_id}\n              value: owned\n            - name: submariner.io\n              value: gateway\n          userDataSecret:\n            name: worker-user-data\n          publicIp: true\n"
      + vars     = {
          + "aws_region"         = "us-east-1"
          + "az"                 = "us-east-1d"
          + "cluster_id"         = "cluster-a-kv9ft"
          + "public_subnet_name" = "cluster-a-kv9ft-public-us-east-1d"
          + "rhos_ami_id"        = "ami-08f17f5bd2210c9fa"
          + "submariner_sg_name" = "cluster-a-kv9ft-submariner-gw-sg"
        }
    }

```

My cluster-b is in us-east-2. In the above output, you can see that its referring to us-east-1

**Comment by manosnoam** [comment]
@sridhargaddam  can you post output of: `bash -x ./prep_for_subm.sh cluster-b` ?

I think it happens since it skips re-downloading of `ocp-ipi-aws-prep` directory from github, since it already exists locally:
https://github.com/submariner-io/submariner/blob/67142065ce6f2b0ae8c4e7b5efc94ef80489ff3b/tools/openshift/ocp-ipi-aws/prep_for_subm.sh#L67

This check is by intention, since it allows the user to avoid overriding his local `ocp-ipi-aws-prep` directory (which might include custom Terraform yamls, etc) - with the latest files from github master. For example, when using a specific branch of that script.

We could probably make this as optional choice, whether to override local files or not, but untill then I would recommend to run the script from a different directory, so it will re-download files.

**Comment by manosnoam** [comment]
@mangelajo, @sridhargaddam ,
The change #877 will break usage of the script, if assuming that downloading `submariner/tools/openshift/ocp-ipi-aws/` and modifying terraform yamls (e.g. to change hardcoded ports), will be the actual yamls.

However since #877 adds:
```
mkdir -p $OCP_INS_DIR/submariner_prep
cd $OCP_INS_DIR/submariner_prep
```
any change to the downloaded yamls will be ignored, as the script will redownload the yamls.

**Comment by manosnoam** [comment]
@sridhargaddam , @mangelajo , @skitt , @nyechiel 
That's my case:
1) I need to have unique ports, not 4500 and 500 on Terraform.
2) I download the whole `/tools/openshift/ocp-ipi-aws` directory (as part of `git clone` of the desired Submariner branch).
3) I update the ports to 4501, 501.
4) I run the script:

--> **Before** #877 patch: 
OSP-AWS job **succeeded** - since it did not re-downloaded the yaml from github, and used the local yamls (with the updated ports):
https://qe-jenkins-csb-skynet.cloud.paas.psi.redhat.com/job/Submariner-OSP-AWS/847/Test-Report/

--> **After** #877 patch: 
OSP-AWS job **failed** - because it re-downloads the directory, and ignores the yamls that I changed:
https://qe-jenkins-csb-skynet.cloud.paas.psi.redhat.com/job/Submariner-OSP-AWS/848/Test-Report/

In addition, #877 may introduce a new problems:

5) The script will always re-download files from github **master** branch.

6) Anyone should be able to alter the local yamls, and expect the script to use the local changes. But with #877 the script will ignore the local changes.

7) What if the OCP install directory (where you specify as destination for download in #877) - is read only? The script will fail to download anything into it.

**Comment by manosnoam** [comment]
Closing this issue, as I opened bug: https://github.com/submariner-io/submariner/issues/880
